apiVersion: v1
kind: Service
metadata:
  name: bh-student-portal
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bh-student-portal
  type: NodePort
  ports:
    - name: http
      port: 4001
      targetPort: 4001
      protocol: TCP
