import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Documents and Labs',
    description: 'Generated by BootcampsHub',
};
import { ReactNode } from 'react';

function layout({ children }: { children: ReactNode }) {
    return <div>{children}</div>;
}

export default layout;
