import { Metadata } from 'next';
import React, { ReactNode } from 'react';
export const metadata: Metadata = {
    title: 'Chats',
    description: 'Generated by BootcampsHub',
};
function layout({ children }: { children: ReactNode }) {
    return <div className='w-full h-full'>{children}</div>;
}

export default layout;
