# Default values for ts4u-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: ms-production

limits:
  cpu: "1000m"
  memory: "2Gi"

requests:
  cpu: "500m"
  memory: "1Gi"

host: portal.bootcampshub.ai

image:
  name: bh-student-portal
  repository: ts4udocker/bh-student-portal
  tag: staging-latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  name: regcred