import { createSlice } from '@reduxjs/toolkit';

const initialState: Record<string, string> = {};

const navigationSlice = createSlice({
    name: 'navigation',
    initialState,
    reducers: {
        setNavigation: (state, action) => {
            return action.payload;
        },
    },
});

// Export actions generated by createSlice
export const { setNavigation } = navigationSlice.actions;

// Export the reducer
export default navigationSlice.reducer;
