import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    programs: [],
    courses: [],
    services: [],
};

const programSlice = createSlice({
    name: 'program',
    initialState,
    reducers: {
        setPrograms: (state, action) => {
            state.programs = action.payload;
        },
        setCourses: (state, action) => {
            state.courses = action.payload;
        },
        setServices: (state, action) => {
            state.services = action.payload;
        },
    },
});

// Export actions generated by createSlice
export const { setPrograms, setCourses, setServices } = programSlice.actions;

// Export the reducer
export default programSlice.reducer;
